resolver: lts-9.17

packages:
- '.'
- location:
    git: git@github.com:packetloop/datadog.git
    commit: d7c5b246e02677596ca03bf699c490d0c4470066
  extra-dep: true
- location:
    git: git@github.com:packetloop/hs-arbor-logger.git
    commit: 5cb8c29152fd3a5c0a96ae6c02b21ee1fba9ec92
  extra-dep: true
- location:
    git: git@github.com:haskell-works/hw-xml.git
    commit: 18aa15f3818d67e610f592217bdf4f0192f1ee90
  extra-dep: true

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
  - avro-0.2.0.0
  - hedgehog-0.5
  - hw-balancedparens-0.2.0.0
  - hw-bits-0.6.0.0
  - hw-conduit-0.2.0.1
  - hw-excess-0.2.0.0
  - hw-hedgehog-0.1.0.1
  - hw-hspec-hedgehog-0.1.0.0
  - hw-int-0.0.0.1
  - hw-kafka-avro-1.3.0
  - hw-kafka-client-2.2.0
  - hw-kafka-conduit-2.0.0
  - hw-parser-0.0.0.2
  - hw-prim-0.4.0.3
  - hw-rankselect-0.10.0.1
  - hw-rankselect-base-0.2.0.1
  - pure-zlib-0.6

# Override default flag values for local packages and extra-deps
flags: {}

extra-package-dbs: []

# Added docker build configuration
# but disabled docker build by default.
# "stack --docker build" will use this configuration.
docker:
  enable: false
  repo: "fpco/stack-build:latest"
  auto-pull: true
  env:
    - "LD_LIBRARY_PATH=docker/rdkafka/lib"
    - "LD_INCLUDE_PATH=docker/rdkafka/include/librdkafka"
